sudo: required
language: csharp
solution: app/ECS.SampleApp.sln
mono: none
dotnet: 3.1.101
services:
    - docker
script:
 - chmod +x ./scripts/deploy_envs.sh
 - chmod +x ./scripts/deploy.sh
 - chmod +x ./scripts/build.sh
 - cd scripts && ./build.sh
 - if [ "$TRAVIS_BRANCH" == "master" ]; then ./deploy.sh; fi